version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@sentry/integrations"
    versions:
    - 6.2.4
    - 6.3.0
  - dependency-name: "@sentry/browser"
    versions:
    - 6.2.4
    - 6.3.0
  - dependency-name: core-js
    versions:
    - 3.10.2
  - dependency-name: vue-cli-plugin-i18n
    versions:
    - 2.0.0
    - 2.0.1
    - 2.0.2
    - 2.0.3
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.11
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-unit-jest"
    versions:
    - 4.5.11
    - 4.5.12
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
    - 4.5.12
